# Generated by Django 4.0.2 on 2022-05-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, unique=True, verbose_name='보호자 아이디')),
                ('user_pw', models.CharField(max_length=128, verbose_name='보호자 비밀번호')),
                ('user_name', models.CharField(max_length=16, verbose_name='보호자 이름')),
                ('user_gender', models.CharField(max_length=8, verbose_name='보호자 성별')),
                ('user_resident_number', models.CharField(max_length=16, unique=True, verbose_name='보호자 주민등록번호')),
                ('user_phone_number', models.CharField(max_length=16, unique=True, verbose_name='보호자 연락처')),
                ('user_emergency_number', models.CharField(max_length=16, verbose_name='보호자 비상연락처')),
                ('user_email', models.EmailField(max_length=128, unique=True, verbose_name='보호자 이메일')),
                ('user_address', models.CharField(max_length=128, verbose_name='보호자 주소')),
                ('user_register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='보호자 계정 생성시간')),
            ],
            options={
                'verbose_name': '보호자',
                'verbose_name_plural': '보호자',
                'db_table': 'user_caregiver',
            },
        ),
    ]
